name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build
      run: |
        xcodebuild -project WechatExporter.xcodeproj \
                   -scheme WechatExporter \
                   -configuration Release \
                   -derivedDataPath build
                   
    - name: Create DMG
      run: |
        cd build/Build/Products/Release
        create-dmg \
          --volname "WechatExporter" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "WechatExporter.app" 200 190 \
          --hide-extension "WechatExporter.app" \
          --app-drop-link 600 185 \
          "WechatExporter.dmg" \
          "WechatExporter.app"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WechatExporter
        path: build/Build/Products/Release/WechatExporter.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/Build/Products/Release/WechatExporter.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
