name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        brew install jsoncpp libxml2 sqlite3 libplist
        sudo ln -sf $(brew --prefix)/opt/jsoncpp/include/jsoncpp/json $(brew --prefix)/include/json
        sudo ln -sf $(brew --prefix)/opt/jsoncpp/lib/*.dylib $(brew --prefix)/lib/
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build
      run: |
        xcodebuild -project WechatExporter.xcodeproj \
                   -scheme WechatExporter \
                   -configuration Release \
                   HEADER_SEARCH_PATHS="$(brew --prefix)/include $(SDKROOT)/usr/include/libxml2" \
                   LIBRARY_SEARCH_PATHS="$(brew --prefix)/lib" \
                   OTHER_LDFLAGS="-ljsoncpp" \
                   -derivedDataPath build
                   
    - name: Create DMG
      run: |
        cd build/Build/Products/Release
        mkdir -p dmg
        cp -r WechatExporter.app dmg/
        hdiutil create -volname "WechatExporter" \
                      -srcfolder dmg \
                      -ov \
                      -format UDZO \
                      WechatExporter.dmg

    - name: Debug Path
      run: ls -R build/Build/Products/Release/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WechatExporter-macOS
        path: build/Build/Products/Release/WechatExporter.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/Build/Products/Release/WechatExporter.dmg